name: Terraform CI - Plan

on:
  push:
    branches:
      - main
      - feature2
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Format, Validate and Plan

    runs-on: self-hosted

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_VALUE }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        working-directory: environment/dev
        run: terraform version

      - name: Terraform Format Check
        working-directory: environment/dev
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environment/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: environment/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environment/dev
        run: terraform plan -out=tfplan

      - name: Show Terraform Plan
        working-directory: environment/dev
        run: terraform show -no-color tfplan