name: Terraform CI - Plan

on:
  push:
    branches:
      - main
      - feature2
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Format, Validate and Plan

    # Organization-level self-hosted runner
    runs-on: [self-hosted, Windows, X64]

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_VALUE }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    defaults:
      run:
        working-directory: environment/dev

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform version
      - name: Terraform Version
        run: terraform version

      # 4. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan